### ISSUE TITLE
Outdated homepage-looking webpage

### ISSUE THREAD

**Issue by jaredcasper** [netguy204/roku_media_server#11]
Just got my Roku yesterday and got My Media up and going today.  Everything worked very smoothly except for one small hiccup.  I knew I wanted to install My Media and went to Google. Instead of looking at the forum, I went to the more homepage looking result under it: http://netguy204.github.com/roku_media_server/, as well as http://netguy204.github.com/roku_media_server/README.html, which led me to outdated instructions based on the master branch (which I thought was reasonable to assume was the latest and greatest).   After getting the (old) server going, I remembered seeing that there was a private channel so found instructions to install that and did.  Obviously the updated channel/appspot combo didn't work with the old server.  Didn't take long to figure out what was up though and things went smoothly after I downloaded and ran the new server.

Anyway, you might consider updating those pages or remove them and add a redirect to avoid confusion for future Googlers.

**Comment by netguy204** [comment]
Oops! Thanks for the heads up. I've updated the readme by just merging channel to master since channel really is the only thing that people should be using. I updated the webpage by just funneling people to the readme and the quick instructions. Hopefully having the documentation in fewer places will mean I mess it up less.

Thanks!

**Comment by jaredcasper** [comment]
A couple more things I noticed that don't seem worth opening another issue for:
- There are links to http://netguy204.github.com/roku_media_server/developers_preview.html scattered around that are now broken.  It looks like instructions for installing from source using developer mode aren't immediately available.  I'm assuming that was on purpose.  I guess anybody that wants to do that should be able to figure it out.  Might be nice to have some kind of developers guide though for people that want to contribute.
- The README.textfile points to an older thread on the roku forum instead of the big 100+ page one.  Seems like it should point to the newer main one?
