### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by netguy204** [netguy204/roku_media_server#2]
From umbighouse:
- (_fixed - changed default_) When in an artist's folder, all that artist's songs are displayed, rather than each album. Is this by design? 
- (_fixed_) When in an artist's folder, you cannot navigate out of it up one level without returning to the Roku home screen. If you hit the UP button, it takes you all the way up there. Is this by design? 
- (_planned_) Is there any way to setup an alphabet navigation, so that you could go to a letter, say "M", and see all of the "M" artists without scrolling all the way there? 
- (_planned_) Any thought to how to include a "shuffle" all songs within an artist folder, or even all songs in the collection? 
- Any thought to playlist support? 
- (_added_) Any thought to including the album artwork when viewing a song?

**Comment by netguy204** [comment]
From DeftOne:
- (_fixed_) Not sure if this was mentioned already, but it would be nice if the channel interface would remember where you were previously when navigating back "up" the folder hierarchy. It's a bit inconvenient getting thrown back to the beginning of the collection every time.
- I haven't restarted my machine since getting everything installed, but I'm guessing the Python server will not automatically launch upon startup of my computer, even though you were going to include the scripts umbighouse posted previously. I know it's not difficult to set up manually, but it would be a nice touch to include an option in the installer to automatically create the startup item.

**Comment by netguy204** [comment]
From wizzy1291:

CURRENT REQUESTS: 
Artist Name/Album/Track displayed while songs are playing. 
Pause function. 

...and that's all I need.

**Comment by wizzy1291** [comment]
One more request:

A way to install the client software without the IP address pre-programmed in. A couple of example (I'm sure there are more solutions): 

(1) The client searches the local network for the server; or 
(2) The client has an after-install set-up screen that allows the user to punch in the correct IP address of the server; 
(3) The client always points to (for example) xxx.xxx.xxx.013 and the PC running the server is always assigned a static IP of xxx.xxx.xxx.013 (not ideal but livable). 

This will simplify installation and allow the roll out of a Private Roku Channel.

**Comment by netguy204** [comment]
As most of these issues are closed, I'm closing this thread and opening issue specific ones.
